services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: ["tail", "-f", "/dev/null"]
    network_mode: "service:db"

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    command: ["tail", "-f", "/dev/null"]
    network_mode: "service:backend"

volumes:
  postgres_data: