# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from books.grpc import books_pb2 as books_dot_grpc_dot_books__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in books/grpc/books_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/library.books.BookController/Create',
                request_serializer=books_dot_grpc_dot_books__pb2.BookRequest.SerializeToString,
                response_deserializer=books_dot_grpc_dot_books__pb2.BookResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/library.books.BookController/Destroy',
                request_serializer=books_dot_grpc_dot_books__pb2.BookDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/library.books.BookController/List',
                request_serializer=books_dot_grpc_dot_books__pb2.BookListRequest.SerializeToString,
                response_deserializer=books_dot_grpc_dot_books__pb2.BookListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/library.books.BookController/PartialUpdate',
                request_serializer=books_dot_grpc_dot_books__pb2.BookPartialUpdateRequest.SerializeToString,
                response_deserializer=books_dot_grpc_dot_books__pb2.BookResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/library.books.BookController/Retrieve',
                request_serializer=books_dot_grpc_dot_books__pb2.BookRetrieveRequest.SerializeToString,
                response_deserializer=books_dot_grpc_dot_books__pb2.BookResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/library.books.BookController/Update',
                request_serializer=books_dot_grpc_dot_books__pb2.BookRequest.SerializeToString,
                response_deserializer=books_dot_grpc_dot_books__pb2.BookResponse.FromString,
                _registered_method=True)


class BookControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=books_dot_grpc_dot_books__pb2.BookRequest.FromString,
                    response_serializer=books_dot_grpc_dot_books__pb2.BookResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=books_dot_grpc_dot_books__pb2.BookDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=books_dot_grpc_dot_books__pb2.BookListRequest.FromString,
                    response_serializer=books_dot_grpc_dot_books__pb2.BookListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=books_dot_grpc_dot_books__pb2.BookPartialUpdateRequest.FromString,
                    response_serializer=books_dot_grpc_dot_books__pb2.BookResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=books_dot_grpc_dot_books__pb2.BookRetrieveRequest.FromString,
                    response_serializer=books_dot_grpc_dot_books__pb2.BookResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=books_dot_grpc_dot_books__pb2.BookRequest.FromString,
                    response_serializer=books_dot_grpc_dot_books__pb2.BookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.books.BookController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.books.BookController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.books.BookController/Create',
            books_dot_grpc_dot_books__pb2.BookRequest.SerializeToString,
            books_dot_grpc_dot_books__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.books.BookController/Destroy',
            books_dot_grpc_dot_books__pb2.BookDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.books.BookController/List',
            books_dot_grpc_dot_books__pb2.BookListRequest.SerializeToString,
            books_dot_grpc_dot_books__pb2.BookListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.books.BookController/PartialUpdate',
            books_dot_grpc_dot_books__pb2.BookPartialUpdateRequest.SerializeToString,
            books_dot_grpc_dot_books__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.books.BookController/Retrieve',
            books_dot_grpc_dot_books__pb2.BookRetrieveRequest.SerializeToString,
            books_dot_grpc_dot_books__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.books.BookController/Update',
            books_dot_grpc_dot_books__pb2.BookRequest.SerializeToString,
            books_dot_grpc_dot_books__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
